import { Button, Code, Heading, Text } from '@chakra-ui/core';
import Head from 'next/head'
import { useAuth } from '@/lib/auth'
import styles from '@/styles/Home.module.css'

export default function Home() {
  const auth = useAuth();
  return (
    <div>
      <Head>
        <title>Fabulous Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>Fabulous Feedback</Heading>
        <Text>
          Current User:{' '}
          <Code>{auth.user ? auth.user.email : 'None'}</Code>
        </Text>
        {auth.user ? (
          <Button onClick={(e) => auth.signout()}>Sign Out</Button>
          ) : (
          <Button onClick={(e) => auth.signinWithGithub()}>Sign In</Button>
        )}
      </main>
    </div>
  )
}
